### ISSUE TITLE
Errors generating API from Kubernetes swagger.json

### ISSUE THREAD

**Issue by wstrange** [dart-ogurets/dart-openapi-maven#1]
First of all- thanks for this plugin!

Let me know if this issue should be filed upstream. I encountered a few errors when attempting to generate an API from  https://github.com/kubernetes/kubernetes/blob/master/api/openapi-spec/swagger.json

This is a *very* complex API spec- so probably worst case for the generator. 

The generated API has the following problems:

```
Future<String> connectCoreV1DeleteNamespacedPodProxyWithPath(String name, String namespace, String path, {Options options, String path2 }) async {
    
// some stuff deleted for brevity...
    if(path == null) {
     throw ApiException(400, 'Missing required param: path');
    }

    // create path and map variables
    final path = '/api/v1/namespaces/{namespace}/pods/{name}/proxy/{path}'.replaceAll('{' + 'name' + '}', name.toString()).replaceAll('{' + 'namespace' + '}', 
```

The issue above is that `path` is both a method argument and a local variable.  One of the variable name needs to be updated to make it unique.

The next issue the `mapFromJson` method that gets generated in several places:

```
// examples
 extra = List.mapFromJson(json['extra']);
 disruptedPods = DateTime.mapFromJson(json['disruptedPods']);

```
There is no such static method `mapFromJson` on these classes.

Next issue:
A variable name is generated using a $ prefix:

```
 if ($ref != null) {
        json['$ref'] = serializer.serialize($ref);
    }
```

The $ prefix is I think not a legal Dart variable name? It gets interpolated in the string.

**Comment by rvowles** [comment]
The first two are definitely this plugin and should be fixed. I'm
suspicious of the third though. $ref being in the wrong place is likely a
does issue, but I can still look into it.

I didn't know k8s even had an openapi spec so this is pretty cool news,
especially with native compile for Dart!

**Comment by rvowles** [comment]
So the issue is this additionalProperties concept - https://swagger.io/docs/specification/data-models/dictionaries/ - which the Dart generator does not at the moment support. I'm looking into it.

**Comment by rvowles** [comment]
@wstrange I have a branch called additional-props that I am working through. I still have an issue with the DateTime and Object types. k8s is defining an empty object as a generic "json" type - which I will need to map to a dynamic I think. The DateTime issue would probably best be solved using Dart's new helper functions - what is your use case, i.e. can I use Dart 2.6+ or will that prevent you from being able to use this?

**Comment by wstrange** [comment]
Yea - that `mapFromJson` method is weird. Maybe an extension method on type Object works?

I can def. use Dart 2.7 (or later). This is low priority for me (mostly a side project to see if I can write an operator in Dart!) - so not urgent.  Thanks for looking at this!!

**Comment by rvowles** [comment]
Given the use case it's used for (to represent any json object) I think I
will try and map it to dynamic instead of Object and drop the mapFromJson.
The datetime I'll provide the helper method for and we should be sorted 😁

**Comment by rvowles** [comment]
I have been working on this, i now have it generating but I don't actually know if it works, k8s is a very complex api with those additional property fields. I have a mind to release it and we can work from there @wstrange ?

**Comment by wstrange** [comment]
Yea - I think that is fine. I will hopefully have some time in January to
take it for a quick spin.

Thanks for your efforts on this!

**Comment by rvowles** [comment]
2.9 should be much better with this @wstrange in case you want to poke at it again some time.

**Comment by wstrange** [comment]
I gave it another spin tonight using https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/swagger.json

This is quite the torture test... 
There are quite a few errors, but I suspect most have the same root cause.

Lots of these
error: getter `inner` is not defined
```
  copy.inner = inner ?? (this.inner == null ? {} : this.inner.map((k, v) => MapEntry(k, v.copyWith());
```

Missing `)`  (looks legit - parens are not balanced)

``` 
copy.inner = inner ?? (this.inner == null ? {} : this.inner.map((k, v) => MapEntry(k, y.copyWith());
```


Undefined name `y`
```
              copy.inner = inner ?? (this.inner == null ? {} : this.inner.map((k, v) => MapEntry(k, y.copyWith());

```
I suspect `y` was supposed to be `v`

**Comment by rvowles** [comment]
@wstrange this now compiles and generates what appears to be correct code but there is a *lot* to the k8s API. The 3.1 version has been tested against the k8s API.

**Comment by wstrange** [comment]
I was able to get it to generate without errors. You are right - this is a monster API!
Thanks for your work on this.
