### ISSUE TITLE
support nullsafety

### ISSUE THREAD

**Issue by rvowles** [dart-ogurets/dart-openapi-maven#24]
@robertcsakany - there is a null safety branch which uses a new version of the openapi common dart that is not released. Not sure if you want to invest the time to run it across your code? It generates code ok, I haven't actually run it up to test it end to end yet.

**Comment by robertcsakany** [comment]
There are a tons of dependencies which are not nullsafe and we are using. (around 40% of used dependencies have no null safety support) - so now hard to test, but we would like to use as soon as possible. What I can do compile the code, but running tests can be done when every of our dependency will be nullsafe.

**Comment by vishna** [comment]
It should be OK to include null safe dependencies in a not null safe project. Any app right now does it since Flutter 2.0. It might be even better to drop support for non null safe code generation in 4.3.

**Comment by rvowles** [comment]
I'm working here, its crazy hard to do this as it turns out and maintain support for the prior version. I have a lot of code using it, so I have to sort it out!

**Comment by rvowles** [comment]
One significant change is that required fields are now null safe. That means the constructor has changed to enable you to pass all fields on construction, but have them named. So User with a required field of email for example you now have to use User(email: email) whereas before you could use User()..email = email.

**Comment by rvowles** [comment]
- 5.0 - is a significant departure and you will need to use the public Dart tool to migrate your code https://pub.dev/packages/openapi_migrate/versions/1.0.0
It allows the use of null safe code by adding in the extra _additionalProperty_ `nullSafe`. It will also allow you to assume (and ensure
defaults are set) null safety for all arrays that are otherwise not declared such in your OpenAPI yaml (by making them empty arrays)
by the use of `nullSafe-array-default`. 

It is recommended for 5.0 that you do an intermediate step and regenerate your existing code without these null safe functions turned on,
and use the `openapi_migrate` tool on your code. Its likely you will need to run it multiple times to catch everything. When you are ready
to move your whole project to null safety, you will be able to regenerate your API with the additionalProperty flags and then do the normal
`dart migrate` process. We are doing this with our codebase over at FeatureHub (https://featurehub.io).

Another significant departure for 5.0 is that it enforces return vaulues - you cannot return a status code from an API that is not declared in
your OpenAPI.
