### ISSUE TITLE
Support List<AnyOf<Type>> fields with discriminator

### ISSUE THREAD

**Issue by vishna** [dart-ogurets/dart-openapi-maven#25]
👋

I've added a very limited support for `anyOf` when used in lists and combined with a discriminator.

More info on the topic:
https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/

## Problem

Here's an example schema file covering the issue:
https://github.com/vishna/example_openapi_anyof/blob/main/anyOf.yaml

The current implementation will generate a following `FruitBasket` class with this `fruits` field:

```dart
List<AnyOfmyApplemyBanana> fruits = [];
```

The generated package doesn't compile since the class `AnyOfmyApplemyBanana` doesn't exists.

##  Solution

The fix generates code for the missing class, it looks something like this:

```dart
class AnyOfMyAppleMyBanana {
  AnyOfMyAppleMyBanana();

  dynamic _value;
  dynamic get value => _value;

  @override
  String toString() {
    return 'AnyOf<MyApple,MyBanana>[value=$_value]';
  }

  fromJson(Map<String, dynamic> json) {
    if (json == null) return;

    final discriminator = json[r'type'];

    if (discriminator == null) {
      return;
    }

    switch (discriminator) {
      case r'apple':
        _value = MyApple.fromJson(json);
        break;
      case r'banana':
        _value = MyBanana.fromJson(json);
        break;
    }
  }

  AnyOfMyAppleMyBanana.fromJson(Map<String, dynamic> json) {
    fromJson(json); // allows child classes to call
  }

  Map<String, dynamic> toJson() => LocalApiClient.serialize(_value);

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) {
      return true;
    }

    if (other is AnyOfMyAppleMyBanana && runtimeType == other.runtimeType) {
      return _value == other._value;
    }

    return false;
  }

  @override
  int get hashCode {
    var hashCode = runtimeType.hashCode;

    if (_value != null) {
      hashCode = hashCode * 31 + _value.hashCode;
    }

    return hashCode;
  }

  AnyOfMyAppleMyBanana copyWith() {
    final copy = AnyOfMyAppleMyBanana();
    copy._value = _value?.copyWith();
    return copy;
  }

  static List<AnyOfMyAppleMyBanana> listFromJson(List<dynamic> json) {
    return json == null
        ? <AnyOfMyAppleMyBanana>[]
        : json.map((value) => AnyOfMyAppleMyBanana.fromJson(value)).toList();
  }
}
```

I've added a sample project with a building script here:
https://github.com/vishna/example_openapi_anyof

**Comment by rvowles** [comment]
I'm sorry I missed this, my email got lost for 6 days. 

Its interesting, but its not quite what I would use as the solution - with the null safety turning up, and I would prefer to use strong types whenever possible. I'm working on null safety now but its a really tricky one. 

I would prefer here that this AnyOfMyAppleMyBanana had a banana and an apple field, and then a getter that you could use with the dynamic type if you wished. I would also prefer the discriminator was turned into an embedded enum as well. 

Thoughts?

**Comment by vishna** [comment]
Just returned from vacations, I see your work on null safety is merged now - I'm going to check it out and see what broke in my PR 😅

So... as for the fields, I'd rather have casting methods, e.g.:

```dart
item.asMyBanana()
item.asMyApple()
```

What do you think?

Speaking of embedded enums, did you mean something like that?

```dart
enum AnyOfDiscrimnatorMyAppleMyBanana { myApple, myBanana }

item.as(AnyOfDiscrimnatorMyAppleMyBanana.myApple)
```

**Comment by rvowles** [comment]
yes, that would work - that would definitely work. It sort of goes against null safety and performance but that stuff is a can of worms and I can always swap it around later if I want and not break your API to it.

**Comment by vishna** [comment]
so I've also hidden this extra generation behind `listAnyOf` flag, other than that, this is what you'll get for nullsafe:

```dart
part of generated_lib.api;

class AnyOfMyAppleMyBanana {
  AnyOfMyAppleMyBanana();

  late dynamic _value;
  dynamic get value => _value;

  @override
  String toString() {
    return 'AnyOf<MyApple,MyBanana>[value=$_value]';
  }

  fromJson(Map<String, dynamic>? json) {
    if (json == null) return;

    final discriminator = json[r'type'];

    if (discriminator == null) {
      return;
    }

    switch (discriminator) {
      case r'apple':
        _value = MyApple.fromJson(json);
        break;
      case r'banana':
        _value = MyBanana.fromJson(json);
        break;
    }
  }

  AnyOfMyAppleMyBanana.fromJson(Map<String, dynamic>? json) {
    fromJson(json); // allows child classes to call
  }

  Map<String, dynamic> toJson() => LocalApiClient.serialize(_value);

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) {
      return true;
    }

    if (other is AnyOfMyAppleMyBanana && runtimeType == other.runtimeType) {
      return _value == other._value;
    }

    return false;
  }

  @override
  int get hashCode {
    var hashCode = runtimeType.hashCode;

    if (_value != null) {
      hashCode = hashCode * 31 + _value.hashCode;
    }

    return hashCode;
  }

  AnyOfMyAppleMyBanana copyWith() {
    final copy = AnyOfMyAppleMyBanana();
    copy._value = _value.copyWith();
    return copy;
  }

  static List<AnyOfMyAppleMyBanana> listFromJson(List<dynamic>? json) {
    return json == null
        ? <AnyOfMyAppleMyBanana>[]
        : json.map((value) => AnyOfMyAppleMyBanana.fromJson(value)).toList();
  }

  MyApple asMyApple() => _value as MyApple;
  MyBanana asMyBanana() => _value as MyBanana;

  dynamic as(AnyOfDiscriminatorMyAppleMyBanana type) {
    switch (type) {
      case AnyOfDiscriminatorMyAppleMyBanana.MyApple:
        return _value as MyApple;
      case AnyOfDiscriminatorMyAppleMyBanana.MyBanana:
        return _value as MyBanana;
    }
  }
}

enum AnyOfDiscriminatorMyAppleMyBanana {
  MyApple,
  MyBanana,
}
```

need to rebase my PR and it should be good to go, I guess

**Comment by vishna** [comment]
PR ready for a review ✅

**Comment by rvowles** [comment]
Ok, so a few things - it looks generally fine, I'm happy with it. However I would do a few things,

(1) Include the enum in the hashcode
(2) Include a scenario in the it/k8s/test.yml and its/k8s_null/test.yml files and make sure they compile ok
(3) consider making the scenario complicated and simple, so a simple type, a list, and an additional properties. I can't see how they'd fail, it looks good but you never know if I've put something in that is going to cause complications
(4) you are creating a scenario where the _value could never receive a value, are you sure you don't want to make it a dynamic? in null safe? (this is also something i need to review for the generated classes)
(5) consider adding tests into the integration tests (under the it folder) just to make sure some change in the future doesn't break your functionality.

I use the SampleRunner to do this and iterate on it, so I can do all of these things for you, it just means it will take longer for me to get done as I have releases to get to in my other projects.

**Comment by vishna** [comment]
> 1) Include the enum in the hashcode

It's not a part of the object. I could make it a part of the object, however I'd rather just delegate hashCode to the underlying object (since it's supposed to always be there) and not do it 😅

__2 & 3:__ can do whenever I have more time (next week I hope).

__4:__ I thought about it, but that should rather be on the List<AnyOfClass?> level. Then you'd have some items in the list null, representing the absence of the value. AnyOfClass is a "union" (and artificial construct) so there should always be a value imo.
__5:__ can do whenever I have more time (next week I hope).

**Comment by vishna** [comment]
added checklist to PR, probably best to track it there (also easier to review code and leave comments)
