### ISSUE TITLE
Is it possible to opt in for generating abstract contract classes?

### ISSUE THREAD

**Issue by yberstad** [dart-ogurets/dart-openapi-maven#3]
Hi!

Thanks for this plugin, great job! 

Is it possible to opt in for generating abstract classes, to ease the testability?

Instead of this:
```dart
class TravelApi {
  final ApiClient apiClient;

  TravelApi(this.apiClient) : assert(apiClient != null);

  Future<MyBookingsResponse> activeBookings({Options options}) async {
```

Could we get the option to generate something along this?
```dart
abstract class TravelApiContract {
  Future<MyBookingsResponse> activeBookings({Options options});
}

class TravelApi implements TravelApiContract {
  final ApiClient apiClient;

  TravelApi(this.apiClient) : assert(apiClient != null);

  @override
  Future<MyBookingsResponse> activeBookings({Options options}) async {
```

I think this would greatly improve the possibility for testing...

**Comment by rvowles** [comment]
You know that in Dart every class is also an interface right? Normal you
would just use the existing class in an implements but extend Mock from
Mockito?

**Comment by yberstad** [comment]
Thanks for your very quick response! 

No, I was not aware of that. I have now had the time to test this out, and it works perfectly.  Thanks!
