### ISSUE TITLE
v5.2 breaks existing code with many "Try calling using ?. instead."

### ISSUE THREAD

**Issue by cws-alb** [dart-ogurets/dart-openapi-maven#37]
```
        <groupId>org.openapitools</groupId>
        <artifactId>openapi-generator-maven-plugin</artifactId>
        <version>5.1.0</version>

            <groupId>com.bluetrainsoftware.maven</groupId>
            <artifactId>openapi-dart-generator</artifactId>
            <version>5.2</version>

                <additionalProperty>nullSafe</additionalProperty>
```

The generation of code by the new 5.2 generator causes many breaks in the code similar to this:

```
Error: Method 'map' cannot be called on 'List<Staff>?' because it is potentially null.
 - 'List' is from 'dart:core'.
 - 'Staff' is from 'package:oas/api.dart' ('...').
Try calling using ?. instead.
        final _copy_admins = (admins == null) ? [] as List<Staff>? : ((List<Staff>? data) { return         data.map((data) =>   
```

**Comment by rvowles** [comment]
Ok, you could fix this by adding the second null safe additional property for lists "nullSafe-array-default". Clearly I didn't test enough with the use case of people not using those two together!

**Comment by cws-alb** [comment]
Super. I’ll give it a whirl and feedback. 

I’m grateful for all you do. Thank you.

**Comment by rvowles** [comment]
The next version will do away with the option for nullable arrays, their content will simply be checked as required or not on send and if they are empty, they will not be sent.
