### ISSUE TITLE
More documentation about testing this package

### ISSUE THREAD

**Issue by vishna** [dart-ogurets/dart-openapi-maven#41]
I think this is a great package and is not that overwhelming as `https://github.com/OpenAPITools/openapi-generator` to work with.

That said it would probably benefit the project having some docs on HOWTO test. Moreover adding e.g., GitHub Action that runs those test would give you a nice feedback when making a PR. I'm happy to add this.

**Comment by rvowles** [comment]
You can run the tests locally by just using `mvn clean verify` - but @IrinaSouth works for Microsoft and with Github so I could probably ask her to do it as she has done it for me :-)

HOWTO's i'm happy to have included! I was planning on writing a series of Medium articles as this is one of four plugins (Rails, Java/Jersey, Dart and Typescript Axios) that I look after.

**Comment by vishna** [comment]
you might also want to enable `Discussions` - it might be a useful place for people asking questions (and looking for answers)  - works like a little reddit
