### ISSUE TITLE
replace spaces with underscores in (enum) identifiers

### ISSUE THREAD

**Issue by NANASHI0X74** [dart-ogurets/dart-openapi-maven#46]
Hi, I've just ran into a problem trying out this generator (switching from one of the openapi-generator-cli default ones). Our Api defines an enum with a bunch of languages and some of the names of these languages contain spaces. The generated code then contains enum definitions where individual enum values contain spaces , for example
```dart
enum languages{
..., cape Verdean,...
}
```
dart sees these as two seperate identifiers without a comma in between, which is invalid. One way to fix this may be to replace spaces with underscores in the enum value identifiers.

The relevant part of my spec looks something like this:
```yaml
    LanguageEnum:
      enum:
      ...
      - Cape Verdean
      ...
```

**Comment by rvowles** [comment]
ok - i wonder if pure number enums would cause issues as well.

**Comment by rvowles** [comment]
try using 5.7

**Comment by NANASHI0X74** [comment]
great! This solves that issue. Unfortunately there are still a few more problems, I will open new issues

**Comment by NANASHI0X74** [comment]
I've decided that this seems to be the best available null-safe code generator out there, so I'll invest some more time to analyse what all the errors are that I run into, and will be posting a ~slew of issues~ describing them if that's ok :p
Turns out I found three issues: #48 #49 #50
When I've identified all the issues I can try and help fix them myself as well

**Comment by rvowles** [comment]
Sounds good to me!
