### ISSUE TITLE
Wrong header assignment in api delegate class

### ISSUE THREAD

**Issue by PiotrMitkowski** [dart-ogurets/dart-openapi-maven#51]
When there are custom headers in schema, the generator creates the code, where an optional `String?` header value is assigned to a headers map of type `<String, String>{}`.

<details>
<summary>schema:</summary>
<br>
<pre>
openapi: 3.0.1
info:
  title: Sample API
  description: My sample API schema
  license:
    name: Name
    url: 'https://myapi.com'
  version: v2
paths:
  /api/v2/User:
    get:
      tags:
        - User
      summary: Get current user
      parameters:
        - name: Accept-Language
          in: header
          schema:
            type: string
      responses:
        '200':
          description: Success
</pre>
</details>

<details>
<summary>generated api file:</summary>
<br>
<pre>
part of sample.api;

// This file is generated by https://github.com/dart-ogurets/dart-openapi-maven - you should not modify it
// log generation bugs on Github, as part of the license, you must not remove these headers from the Mustache templates.

class UserApi {
  final UserApiDelegate apiDelegate;

  UserApi(ApiClient apiClient) : apiDelegate = UserApiDelegate(apiClient);

  /// Get current user
  ///
  ///
  Future<void> apiV2UserGet({Options? options, String? acceptLanguage}) async {
    final response = await apiDelegate.apiV2UserGet(
        options: options, acceptLanguage: acceptLanguage);

    if (![200].contains(response.statusCode)) {
      throw ApiException(500,
          'Invalid response code ${response.statusCode} returned from API');
    }

    if (response.statusCode == 204) {
      return;
    }

    final __body = response.body;
    if (response.statusCode >= 400) {
      throw ApiException(response.statusCode,
          __body == null ? null : await decodeBodyBytes(__body));
    }

    throw ApiException(500, 'Invalid response received for 204 based API');
  }

  /// Get current user
  ///
  ///
}

class UserApiDelegate {
  final ApiClient apiClient;

  UserApiDelegate(this.apiClient);

  Future<ApiResponse> apiV2UserGet(
      {Options? options, String? acceptLanguage}) async {
    // create path and map variables
    final __path = '/api/v2/User';

    // query params
    final queryParams = <QueryParam>[];
    final headerParams = <String, String>{}
      ..addAll(options?.headers?.cast<String, String>() ?? {});
    if (headerParams['Accept'] == null) {
      // we only want to accept this format as we can parse it
      headerParams['Accept'] = 'application/json';
    }

    headerParams['Accept-Language'] = acceptLanguage;    // <------ problem lies here - acceptLanguage is 'String?' and headerParams value should be 'String'

    final authNames = <String>[];
    final opt = options ?? Options();

    final contentTypes = [];

    if (contentTypes.isNotEmpty && headerParams['Content-Type'] == null) {
      headerParams['Content-Type'] = contentTypes[0];
    }

    opt.headers = headerParams;
    opt.method = 'GET';

    return await apiClient.invokeAPI(__path, queryParams, null, authNames, opt);
  }

  Future<void> apiV2UserGet_decode(Stream<List<int>> body) async {}
}
</pre>
</details>

I was wondering if the `api.mustache` can just provide a default, empty value for header, like below:
```
    {{#headerParams}}
        headerParams['{{baseName}}'] = {{paramName}} ?? '';
    {{/headerParams}}
```

What do you think?

**Comment by rvowles** [comment]
I swear I started work on this...
