### ISSUE TITLE
Cannot build project locally

### ISSUE THREAD

**Issue by PiotrMitkowski** [dart-ogurets/dart-openapi-maven#61]
After cloning the project and running `mvn clean verify`, I get the following error: 
<details>
<summary>Error from Maven:</summary>
<br>
<pre>
[INFO] --- maven-invoker-plugin:3.2.1:run (integration-test) @ openapi-dart-generator ---
[INFO] Building: k8s_null/pom.xml
[INFO] run post-build script verify.groovy
[INFO]   The post-build script did not succeed. assert !proc.exitValue()
       ||    |
       ||    1
       |java.lang.UNIXProcess@27dc81be
       false
[INFO]           k8s_null/pom.xml ................................. FAILED (19.5 s)
[INFO] Building: k8s/pom.xml
[INFO] run post-build script verify.groovy
[INFO]   The post-build script did not succeed. assert !proc.exitValue()
       ||    |
       ||    1
       |java.lang.UNIXProcess@6eb5b9e7
       false
[INFO]           k8s/pom.xml ...................................... FAILED (18.2 s)
[INFO] -------------------------------------------------
[INFO] Build Summary:
[INFO]   Passed: 0, Failed: 2, Errors: 0, Skipped: 0
[INFO] -------------------------------------------------
[ERROR] The following builds failed:
[ERROR] *  k8s_null/pom.xml
[ERROR] *  k8s/pom.xml
</pre>
</details>

I've checked the `build.log` and it gives me the following errors:
<details>
<summary>Error from k8s build.log:</summary>
<br>
<pre>
[INFO] ( pub run test test/api_tests.dart )
gave the following error: 
[ERROR] Failed to precompile test:test:
../../../../../../../.pub-cache/hosted/pub.dartlang.org/analyzer-0.41.2/lib/src/error/best_practices_verifier.dart:258:50: Error: The property 'displayString' is defined in multiple extensions for 'TargetKind' and neither is more specific.
 - 'TargetKind' is from 'package:meta/meta_meta.dart' ('../../../../../../../.pub-cache/hosted/pub.dartlang.org/meta-1.7.0/lib/meta_meta.dart').
Try using an explicit extension application of the wanted extension or hiding unwanted extensions from scope.
        var kindNames = kinds.map((kind) => kind.displayString).toList()
                                                 ^^^^^^^^^^^^^
../../../../../../../.pub-cache/hosted/pub.dartlang.org/analyzer-0.41.2/lib/src/error/best_practices_verifier.dart:1950:14: Context: This is one of the extension members.
  String get displayString {
             ^^^^^^^^^^^^^
../../../../../../../.pub-cache/hosted/pub.dartlang.org/meta-1.7.0/lib/meta_meta.dart:91:14: Context: This is one of the extension members.
  String get displayString {
             ^^^^^^^^^^^^^
../../../../../../../.pub-cache/hosted/pub.dartlang.org/analyzer-0.41.2/lib/src/error/best_practices_verifier.dart:260:36: Error: The getter 'commaSeparatedWithOr' isn't defined for the class 'List<dynamic>'.
 - 'List' is from 'dart:core'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'commaSeparatedWithOr'.
        var validKinds = kindNames.commaSeparatedWithOr;
                                   ^^^^^^^^^^^^^^^^^^^^

Assertion failed: 

assert !proc.exitValue()
       ||    |
       ||    1
       |java.lang.UNIXProcess@6eb5b9e7
       false
</pre>
</details>
My Dart version is: 

`Dart SDK version: 2.13.4 (stable)`

It seems that this error comes from this Dart SDK issue: https://github.com/dart-lang/sdk/issues/46687. Ideally, it would be great to update the `test` package to at least `1.16.8`, but will required to update `dio` and `openapi_dart_common`, which might take some time. However, there's a quick workaround - the problem can be solved by adding `analyzer: ^0.40.7` to `pubspec.mustache` as a dev dependency. 
If you have nothing against it, I can take care of this issue. I'll also gladly help with updating the Dart dependencies.

**Comment by rvowles** [comment]
You can add arbitrary imports to your own pubspec.mustache using this mechanism: https://github.com/dart-ogurets/dart-openapi-maven#additional-properties - is this what you mean?

I haven't been tracking updates to Dio, should we update them?

**Comment by PiotrMitkowski** [comment]
I know the additional properties feature and it's very useful for adding any custom dependencies for personal use. However, without the `analyzer` package (or updating the `test` package, that uses analyzer), the tests run through `mvn clean verify` are failing for me due to the bug I mentioned above. I assumed that `pubspec.mustache` should have all the dependencies required to pass the tests and that's why I suggested to add the `analyzer` directly there, not through the additional properties.

**Comment by rvowles** [comment]
Would you like me to release a new version now?

**Comment by PiotrMitkowski** [comment]
I haven't noticed that it affect any of my projects using this generator, it was only preventing me from running the generator tests and fixing other issues, that I've noticed. I don't need it for now 🙂 Thanks!
