### ISSUE TITLE
Incorrect generation of null-safe 2d arrays

### ISSUE THREAD

**Issue by PiotrMitkowski** [dart-ogurets/dart-openapi-maven#62]
Let's say I have the following endpoint in Swagger, returning an object containing 2d array of numbers:
<details>
<summary>Sample schema:</summary>
<br>
<pre>
openapi: 3.0.1
info:
  title: 'Sample API'
  description: Sample API description
  version: v2
paths:
  "/map-point/geometry":
    get:
      tags:
        - "Map Points"
      summary: Retrieves information about map points
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PointGeometry'
components:
  schemas:
    PointGeometry:
      type: object
      properties:
        coordinatesType:
          type: string
          nullable: true
        coordinates:
          type: array
          items:
            type: array
            items:
              type: number
              format: double
          nullable: true
      additionalProperties: false

</pre>
</details>

Running the generator results in having the following `point_geometry.dart` contents (sorry for the formatting - dartfmt can deal with this file as it contains syntax errors):

<details>
<summary>Generated class:</summary>
<br>
<pre>
part of k8s_api.api;

// This file is generated by https://github.com/dart-ogurets/dart-openapi-maven - you should not modify it
// log generation bugs on Github, as part of the license, you must not remove these headers from the Mustache templates.

// PointGeometry
class PointGeometry {
    
      String? coordinatesType;
    
      List<List<double>> coordinates = [];
PointGeometry({ this.coordinatesType,
    List<List<double>>? coordinates,
     }) : this.coordinates = coordinates ?? [];

  @override
  String toString() {
    return 'PointGeometry[coordinatesType=$coordinatesType, coordinates=$coordinates, ]';
  }

  fromJson(Map<String, dynamic>? json) {
    if (json == null) return;
  

        coordinatesType = (json[r'coordinatesType'] == null) ? null : (json[r'coordinatesType'] as String?);

      

        {
final _jsonData = json[r'coordinates'];
coordinates = (_jsonData == null) ? [] : ((dynamic data) { return       (data as List<dynamic>).fromNull().map((data) { ((dynamic data) { return         data?.cast<double>()

;})(data); }).toList()

; }(_jsonData));
} // _jsonFieldName

      
  }

  PointGeometry.fromJson(Map<String, dynamic>? json) {
    fromJson(json); // allows child classes to call
  }

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
  if (coordinatesType != null) {
          json[r'coordinatesType'] = coordinatesType;
    } 
  if (coordinates.isNotEmpty) {
        json[r'coordinates'] = coordinates.map((v) => LocalApiClient.serialize(v)).toList();
    } 
    return json;
  }
  static List<PointGeometry> listFromJson(List<dynamic>? json) {
    return json == null ? <PointGeometry>[] : json.map((value) => PointGeometry.fromJson(value)).toList();
  }

  static Map<String, PointGeometry> mapFromJson(Map<String, dynamic>? json) {
    final map = <String, PointGeometry>{};
    if (json != null && json.isNotEmpty) {
      json.forEach((String key, dynamic value) => map[key] = PointGeometry.fromJson(value));
    }
    return map;
  }

  @override
  bool operator ==(Object? __other) {
    if (identical(this, __other)) {
      return true;
    }

    if (__other is PointGeometry && runtimeType == __other.runtimeType) {
    return 

     coordinatesType == __other.coordinatesType &&
  
        const ListEquality().equals(coordinates, __other.coordinates)    
    ;
    }

    return false;
  }

  @override
  int get hashCode {
    var hashCode = runtimeType.hashCode;

    
          if (coordinatesType != null) {
        hashCode = hashCode * 31 + coordinatesType.hashCode;
            }

    
          if (coordinates.isNotEmpty) {
        hashCode = hashCode * 31 + const ListEquality().hash(coordinates);
        }

    

    return hashCode;
  }

  PointGeometry copyWith({
         String? coordinatesType,
         List<List<double>>? coordinates,
    }) {

  coordinatesType ??= this.coordinatesType;
  coordinates ??= this.coordinates;
  
      final _copy_coordinatesType = coordinatesType;
        final _copy_coordinates = ((List<List<double>> data) { return       data.map((data) { ((data) { return         data.toList()

;})(data); }).toList()

; }(coordinates));

  

    return PointGeometry(
      coordinatesType: _copy_coordinatesType,coordinates: _copy_coordinates,);
  }
}
</pre>
</details>

There are 2 issues with the code above:
- `fromJson` method - the closure with map function for `coordinates` field returns `List<List<double>?>`, while it should be `List<List<double>>`,
- `copyWith` method - `_copy_coordinates` variable is generated as `List<Null>`, while it should be `List<List<double>>?`.

I was able to fix those issues by adding some casts to the target type. I can also see that the closure function for `data.map` for array items in `_array_copy.mustache` is not returning any value (it's missing a `return` statement or it should have a single expression syntax). The second remark applies also to an array part in `_array_from_json.mustache`.

**Comment by rvowles** [comment]
Did you want to issue a PR for it before I release the next one with your update?

**Comment by PiotrMitkowski** [comment]
Yes, I'll work on it next week and would be great to have a new release after a fix to this one.
