### ISSUE TITLE
Feature request: would it be possible to expose the underlying Dio interceptors?

### ISSUE THREAD

**Issue by MagnusJohansson** [dart-ogurets/dart-openapi-maven#64]
Hi,

First , this is a great generator, by far the best I have used yet.

Now I would like to implement caching, using the `dio_cache_interceptor` [package.](https://pub.dev/packages/dio_cache_interceptor )

That would require exposing the Dio interceptor properties, I'll assume.

Would this be possible?

**Comment by rvowles** [comment]
When you create the ApiClient, you can  in a DioClientDelegate, and into that you can pass your own Dio instance.

So: ApiClient("http://basepath", DioClientDelegate(<your-dio-instance>))

**Comment by MagnusJohansson** [comment]
Great, thanks. I stumbled upon an issue though: #65
