### ISSUE TITLE
Exception in copyWith and Map - type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, FilterQuery>?' in type cast

### ISSUE THREAD

**Issue by Maczuga** [dart-ogurets/dart-openapi-maven#75]
I have a schema called "SearchParams" which contains Map<String, FilterQuery> (and is nullable).

Snippets from openapi json file.
```json
"SearchParams": {
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "phrase": {
            "type": "string",
            "nullable": true
        },
        "virtualCategory": {
            "type": "string",
            "nullable": true
        },
        "inDescription": {
            "type": "boolean",
            "nullable": true,
            "default": false
        },
        "pagination": {
            "$ref": "#/components/schemas/PaginationParams"
        },
        "sorting": {
            "type": "string",
            "nullable": true
        },
        "filters": {
            "type": "object",
            "nullable": true,
            "default": {},
            "additionalProperties": {
                "$ref": "#/components/schemas/FilterQuery"
            }
        },
        "categoryId": {
            "type": "integer",
            "nullable": true,
            "default": 0
        },
        "slug": {
            "type": "string",
            "nullable": true
        }
    }
},
"FilterQuery": {
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "values": {
            "type": "string",
            "nullable": true
        },
        "from": {
            "type": "number",
            "format": "float",
            "nullable": true
        },
        "to": {
            "type": "number",
            "format": "float",
            "nullable": true
        }
    }
},
```

Both classes are generated correctly. There is however an issue when trying to execute a copyWith function and my input "filters" value is null.

Currently filters are being copied like this:

```dart
final _copy_filters = (filters == null)
    ? {} as Map<String, FilterQuery>?
    : ((Map<String, FilterQuery>? data) {
        return data?.map((String key, FilterQuery data) => MapEntry<String, FilterQuery>(key, data.copyWith()));
      }(filters));
```

The 2nd line is causing an exception: 
`E/flutter (11643): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, FilterQuery>?' in type cast`

Replacing `{} as Map<String, FilterQuery>?` with `new Map<String, FilterQuery>.from({})` fixes the issue. However - note that there is no nullable `?`. For nullable checks this could be just simplified with null, since both `{} as Map<String, FilterQuery>?` and `new Map<String, FilterQuery>?.from({})` will cause different exceptions.

**Comment by rvowles** [comment]
So you don't need to keep saying "nullable: true" because unless you have a required section, all non-required fields are nullable: true in the Dart OpenAPI generator. I have converted your JSON Schema to YAML and am having a look to see if I can resolve it, but the copyWith logic is pretty tortuous - hopefully you saw you can disable it :-)

**Comment by Maczuga** [comment]
This JSON is autogenerated based on model schema on server. Most of fields are marked as nullable simply because the server allows them to be null. 

I had however to migrate project to another openapi generator due to this issue + overall copyWith being obnoxious to work with for nested classes, so I'll no longer be to assist you with this issue.

**Comment by rvowles** [comment]
yes, copyWith is quite obnoxious and I thought I had the ability to disable it in this generator but I do not. I will add this feature. I am glad another generator worked for you, that is good news!

**Comment by rvowles** [comment]
yes, I see Map<String, FilterQuery>?.from({}) is not valid syntax. I can resolve it by using Map<String, FilterQuery>? as a type but that requires Dart 2.16+ so I think I will stick with being able to disable the copyWith for now.
