### ISSUE TITLE
Incorrect code generation for class hierarchies

### ISSUE THREAD

**Issue by roald-di** [dart-ogurets/dart-openapi-maven#76]
Hi,

I was trying to use the generator with models that use inheritance but I found a few issues:

- constructors are missing parameters for base class fields 
- super constructor is not called
- super call in toJson is missing
- equality operator does not always compile
- copyWith is missing parameters for base class fields 
- this issue is preventing multiple inheritance from working: https://github.com/OpenAPITools/openapi-generator/issues/11846
- there are some issues with empty base classes

I will make a PR for this.

**Comment by rvowles** [comment]
much appreciated!
