### ISSUE TITLE
Make it easier for folks with no Java experience to use

### ISSUE THREAD

**Issue by lukepighetti** [dart-ogurets/dart-openapi-maven#78]
Is there any way to provide a dart CLI wrapper around the CLI version of this tool? I'm trying to use it, and as someone with no experience with Java, I'm finding it very difficult to understand all the context needed to get this up and running.

**Comment by rvowles** [comment]
There already is one AFAIK - I believe this project embeds it along with the others - https://pub.dev/packages/openapi_generator

**Comment by lukepighetti** [comment]
Thanks
