### ISSUE TITLE
Headers are added twice

### ISSUE THREAD

**Issue by Garanas** [dart-ogurets/dart-openapi-maven#9]
The headers (from the 'headerParams' in api.mustache) are added twice to the options:
 - api.mustache at line 112:
```
    opt.headers = headerParams;
    opt.method = '{{httpMethod}}';
```
 - api_client.dart (from the openapi_dart_common-3.0.1 library) at line 60.
```
    options.headers.addAll(_defaultHeaderMap);
    options.headers.addAll(headerParams);
```

The headerParams variable is send along to the invokeAPI function, which ends up executing line 60 of the file in the library. The headers are a Map<key, value> so they should be overridden when adding them again. Something I noticed when walking through the code.

**Comment by rvowles** [comment]
fixed in 3.3
