### ISSUE TITLE
Generation fails with exception 

### ISSUE THREAD

**Issue by gbloggs** [dart-ogurets/dart-openapi-maven#90]
Changes in the underlying camelize method in org.openapitools.codegen.utils.StringUtils means codegen fails when building against the latest version of the maven plugin:

```
        <groupId>org.openapitools</groupId>
        <artifactId>openapi-generator-maven-plugin</artifactId>
        <version>6.2.1</version>
```
[StringUtils] (https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/StringUtils.java)

```
...
    /**
     * Camelize name (parameter, property, method, etc)
     *
     * @param inputWord string to be camelize
     * @param camelizeOption option for the camelize result
     * @return camelized string
     */
    public static String camelize(final String inputWord, CamelizeOption camelizeOption) {
...
```

The class: `DartV3ApiGenerator` has 2 calls to camelize. Only the call on line 166 causes the issue:
```
      name = StringUtils.camelize(name, true)
```

should be replaced with:
```
  name = StringUtils.camelize(name, CamelizeOption.LOWERCASE_FIRST_LETTER)
```

**Comment by rvowles** [comment]
I was thinking just yesterday that I should look at upgrading it to 6.2.1, nice of you to try it out.

**Comment by rvowles** [comment]
This should be on Central now.
